### PR TITLE
RSDK-8569: move module to viam-modules and change namespace to viam

### PR DESCRIPTION
**Pull request by martha-johnston**
tested on linux/arm64, build successfully

### CODE REVIEW

**Review by hexbabe — COMMENTED** [review]
Nice I see that https://app.viam.com/module/viam/viam-revolution-pi the rc was published successfully. Do we need to change `module viam/viam-revolution-pi` -> `github.com/viam-modules/viam-revolution-pi`

**Comment by hexbabe** [comment]
Does the model register successfully on module startup when you add it to a robot?

**Comment by martha-johnston** [comment]
> Nice I see that https://app.viam.com/module/viam/viam-revolution-pi the rc was published successfully. Do we need to change `module viam/viam-revolution-pi` -> `module github.com/viam-modules/viam-revolution-pi`

I don't think we need to add Viam-modules here

**Review by hexbabe — APPROVED** [review]
Cool LGTM

**Pull request merged**
